export  const  companies = [
    {
        "document": "02",
        "firstName": "Maria",
        "lastName": "Gonzalez",
        "nameEmprendimiento": "EcoCleanTech",
        "email": "ecoclean@gmail.com",
        "address": "Avenida Verde #456",
        "description": "EcoCleanTech ofrece productos de limpieza ecológicos y biodegradables para hogares y empresas.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "03",
        "firstName": "Carlos",
        "lastName": "Martinez",
        "nameEmprendimiento": "FitFuel",
        "email": "fitfuel@gmail.com",
        "address": "Calle Fitness #789",
        "description": "FitFuel proporciona suplementos nutricionales y alimentos saludables para atletas y entusiastas del fitness.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "04",
        "firstName": "Luisa",
        "lastName": "Hernandez",
        "nameEmprendimiento": "GreenThumb",
        "email": "greenthumb@gmail.com",
        "address": "Camino Verde #321",
        "description": "GreenThumb ofrece herramientas y suministros para la jardinería orgánica y el cultivo en casa.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "05",
        "firstName": "Ana",
        "lastName": "Lopez",
        "nameEmprendimiento": "ArtisanCrafts",
        "email": "artisancrafts@gmail.com",
        "address": "Plaza Artesanal #567",
        "description": "ArtisanCrafts ofrece una variedad de productos artesanales únicos, desde cerámica hasta joyería hecha a mano.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "06",
        "firstName": "David",
        "lastName": "Ramirez",
        "nameEmprendimiento": "TechGear",
        "email": "techgear@gmail.com",
        "address": "Avenida Tecnológica #890",
        "description": "TechGear ofrece una amplia gama de gadgets y dispositivos electrónicos para entusiastas de la tecnología.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "07",
        "firstName": "Elena",
        "lastName": "Sanchez",
        "nameEmprendimiento": "FashionFusion",
        "email": "fashionfusion@gmail.com",
        "address": "Paseo de la Moda #1122",
        "description": "FashionFusion ofrece ropa y accesorios de moda hechos con materiales sostenibles y técnicas innovadoras.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "08",
        "firstName": "Diego",
        "lastName": "Torres",
        "nameEmprendimiento": "PetParadise",
        "email": "petparadise@gmail.com",
        "address": "Calle de las Mascotas #333",
        "description": "PetParadise ofrece una amplia gama de productos y servicios para el cuidado y la diversión de mascotas.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "09",
        "firstName": "Laura",
        "lastName": "Diaz",
        "nameEmprendimiento": "BookHaven",
        "email": "bookhaven@gmail.com",
        "address": "Calle de los Libros #444",
        "description": "BookHaven ofrece una amplia selección de libros impresos y electrónicos en varios géneros y temas.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "10",
        "firstName": "Gabriel",
        "lastName": "Perez",
        "nameEmprendimiento": "BrewMaster",
        "email": "brewmaster@gmail.com",
        "address": "Calle de la Cerveza #555",
        "description": "BrewMaster ofrece equipos y suministros para la elaboración de cerveza artesanal en casa.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
    {
        "document": "11",
        "firstName": "Sofia",
        "lastName": "Ruiz",
        "nameEmprendimiento": "SparkleGlow",
        "email": "sparkleglow@gmail.com",
        "address": "Avenida Brillante #666",
        "description": "SparkleGlow ofrece productos de belleza y cuidado personal naturales y libres de crueldad.",
        "img": "null",
        "password": "12345",
        "confirmPassword": "12345"
    },
]